name: swimming_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  



  flutter:
    sdk: flutter
     # UI
  
  # Network
  http: ^1.1.0  # ðŸ†• Add this for backend communication
  
  # Date formatting
  
   
    
  # Use older Firebase versions that work with NDK 25
 


  # Firebase & Auth
  firebase_core: ^2.20.0
  firebase_auth: ^4.12.0
  cloud_firestore: ^4.9.0
  firebase_storage: ^11.6.5


  # Google Sign-In
  google_sign_in: ^6.1.5

  # Networking (â¬…ï¸ add this)


  file_picker: ^8.1.2
  video_player: ^2.9.2


  # Utility
  intl: ^0.19.0
  image_picker: ^1.0.4
  shared_preferences: ^2.5.3
 
  # UI
  cupertino_icons: ^1.0.6
  fl_chart: ^0.64.0 # âœ… Added for chart rendering

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    # You can also add specific files like:
    # - assets/images/logo.jpg
